# FIXME(marian): We should change this file when we want to publish aligned layer docker images.
# This file is used for building and pushing images
services:
  node:
    build:
      context: .
      dockerfile: operator.Dockerfile
    image: ghcr.io/layr-labs/incredible-squaring-avs/node:latest
  nodeplugin:
    build:
      context: .
      dockerfile: plugin.Dockerfile
    image: ghcr.io/layr-labs/incredible-squaring-avs/nodeplugin:latest
