name: integration-tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install libudev1
        run: sudo apt update && sudo apt install libudev-dev
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Test
        run: make tests-integration
